on: [push]
jobs:
  build:
  name: Hello world
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v2
  - name: Sample Message
    run: |
      echo This demo file.
      echo Basic workflow: Hello World
